#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x picom >/dev/null || picom &
setxkbmap -option grp:caps_toggle us,ru
xsetroot -cursor_name left_ptr
$HOME/.config/polybar/shapes/scripts/pywal.sh $HOME/Pictures/Wallpapers
$HOME/.config/polybar/shapes/launch.sh
$HOME/.config/dunst/launch.sh

bspc monitor -d I II III IV

bspc config border_width 2
bspc config window_gap 15

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
